const RANDOM_ID_MAX = 10_000;

/**
 * Generates a unique identifier string with a specified prefix.
 *
 * The identifier is constructed by concatenating the prefix and a random number,
 * separated by an underscore. The random number is generated by multiplying
 * `Math.random()` with `RANDOM_ID_MAX`.
 *
 * @param prefix - The prefix to use for the identifier. Defaults to `"node"`.
 * @returns A unique identifier string in the format `${prefix}_${randomNumber}`.
 */
export const getId = (prefix = "node") =>
  `${prefix}_${Math.random() * RANDOM_ID_MAX}`;
